// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqcLpLubduJakxeRemB9Ri-kmPBP1JxL4',
    appId: '1:796656861989:web:b1e90a3c384cdae61dd0cc',
    messagingSenderId: '796656861989',
    projectId: 'antigaspi-6bc03',
    authDomain: 'antigaspi-6bc03.firebaseapp.com',
    storageBucket: 'antigaspi-6bc03.appspot.com',
    measurementId: 'G-5KBY86SSK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL9V18jucchRR58kezpGJzwh5mTQrzrGs',
    appId: '1:796656861989:android:6da1e630bb2996ff1dd0cc',
    messagingSenderId: '796656861989',
    projectId: 'antigaspi-6bc03',
    storageBucket: 'antigaspi-6bc03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE3Bz7hHjMoDGZMVEur8VP-l4L4C8R8Po',
    appId: '1:796656861989:ios:5e1b7f8d751828561dd0cc',
    messagingSenderId: '796656861989',
    projectId: 'antigaspi-6bc03',
    storageBucket: 'antigaspi-6bc03.appspot.com',
    iosClientId: '796656861989-up3ncbctl2r1q5fvo53g74rfnvclnkba.apps.googleusercontent.com',
    iosBundleId: 'com.example.antigaspiLycee',
  );
}
